language: go

go:
  - 1.4
  - tip

install: 
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress

notifications:
  slack:
    secure: OdP+maK3uhlYdaTjImPLnMeSxYcV2Kql/BjPW7uFzK4YVa2gkCDNqBGu8y4i47MbXCmXPutPOSOcIsjQ0Rgevr4fWjWBMXITqfZKF/UqrptIfQGP2T8LKm9TdhBCrtfW4EsBsTpOkgmQyWzihr0Zu1pwoeQ+HAesViuaSdriZGw=
